/** @type {import('tailwindcss').Config} */
const stack = ['Inter', 'Segoe UI', 'system-ui', '-apple-system', 'Helvetica Neue', 'Arial', 'sans-serif'];

module.exports = {
  content: ['./public/**/*.html', './public/assets/*.js'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#6ffbbe',
        'error-container': '#ffdad6',
        'surface-container': '#edeeef',
        'surface-variant': '#e1e3e4',
        'inverse-on-surface': '#f0f1f2',
        'on-surface-variant': '#45464c',
        'on-secondary-fixed': '#002113',
        'on-secondary-container': '#00714d',
        'primary-fixed': '#dce2f7',
        'on-secondary': '#ffffff',
        primary: '#000000',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#4edea3',
        surface: '#f8f9fa',
        'on-background': '#191c1d',
        'surface-container-high': '#e7e8e9',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#005236',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#c0c7d6',
        'on-error': '#ffffff',
        'on-surface': '#191c1d',
        'surface-tint': '#575e70',
        'primary-fixed-dim': '#c0c6db',
        'surface-bright': '#f8f9fa',
        'on-tertiary-container': '#7d8492',
        'inverse-primary': '#c0c6db',
        'tertiary-fixed': '#dce2f3',
        tertiary: '#000000',
        'on-primary': '#ffffff',
        outline: '#76777d',
        secondary: '#006c49',
        'tertiary-container': '#151c27',
        'surface-dim': '#d9dadb',
        'outline-variant': '#c6c6cd',
        'on-tertiary-fixed': '#151c27',
        error: '#ba1a1a',
        warning: '#f59e0b',
        'surface-container-low': '#f3f4f5',
        'on-primary-container': '#7d8497',
        'inverse-surface': '#2e3132',
        'primary-container': '#141b2b',
        'secondary-container': '#6cf8bb',
        'on-primary-fixed-variant': '#404758',
        background: '#f8f9fa',
        'on-primary-fixed': '#141b2b',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-fixed-variant': '#404754',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        unit: '4px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'body-base': stack,
        'display-lg': stack,
        'headline-lg': stack,
        'label-caps': stack,
        'headline-lg-mobile': stack,
        'title-md': stack,
        'body-sm': stack,
      },
      fontSize: {
        'body-base': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
